### ISSUE TITLE
[BUG] Place Order function returns fetch error

### ISSUE THREAD

**Issue by karanbhullar04** [b2broker/exante-node#46]
Place order function returns fetch error on both live and demo API

**To Reproduce**
Create a rest client as mentioned in the readme and run the place order function with the same parameters in the readme

```typescript
import * as Exante from "exante";
async function placeOrder(){
    const version = "3.0";
    const symbolId = "AAPL.NASDAQ";
    const side = "sell";
    const quantity = "1";
    const limitPrice = "10000";
    const duration = "good_till_cancel";
    const orderType = "limit";
    const accountId = "ABC1234.001";
    const order = await client.placeOrder({
        version,
        symbolId,
        side,
        quantity,
        limitPrice,
        duration,
        orderType,
        accountId,
    });
    console.log(order);
}
```

- Node.js version: v12.6.0
- NPM version: 6.14.8
- `exante` version: 1.31.1

**Additional context**
other functions like get account, get last quote are working. The following error is reported on place order:

```
> (node:66150) UnhandledPromiseRejectionWarning: FetchError: Bad Request
>     at Function.fetch (~/node_modules/exante/build/src/rest.js:450:13)
>     at processTicksAndRejections (internal/process/task_queues.js:85:5)
>     at async RestClient.fetch (~/node_modules/exante/build/src/rest.js:36:22)
>     at async RestClient.placeOrder (~/node_modules/exante/build/src/rest.js:291:19)
>     at async placeOrder (~/exchangeAPI/exante.js:47:19)
> (node:66150) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:66150) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by vansergen** [comment]
@karanbhullar04 I could not reproduce the error. The following code worked fine for me:

```typescript
import { RestClient } from "exante";

async function placeOrder() {
  const client_id = "<client_id>";
  const app_id = "<client_id>";
  const shared_key = "<shared_key>";
  const demo = true; // Or change it 
  const client = new RestClient({ client_id, app_id, shared_key, demo });
  const version = "3.0";
  const symbolId = "AAPL.NASDAQ";
  const side = "sell";
  const quantity = "1";
  const limitPrice = "10000";
  const duration = "good_till_cancel";
  const orderType = "limit";
  const [{ accountId }] = await client.getAccounts({ version }); // Make sure you use an existing `accountId`
  const order = await client.placeOrder({
    version,
    symbolId,
    side,
    quantity,
    limitPrice,
    duration,
    orderType,
    accountId,
  });
  console.log(order);
}

placeOrder();
```

Can you add provide more information about the error by adding a try/catch block:
```ts
try {
  await placeOrder();
} catch (error) {
  error.response.text().then(console.log).catch(console.error);
}
```

**Comment by vansergen** [comment]
@karanbhullar04 Please, open the issue again if you still have the same problem.
